/**
 * RMSL's public entry point. A thin barrel: everything the package exports
 * lives in one of the files below, split by concern (the DSL core, the
 * compiler internals every backend shares, and the four backends
 * themselves). Kept as an explicit named re-export list, not `export *`,
 * so a helper one file needs from another doesn't silently become public
 * API just because it had to be `export`ed to cross a file boundary.
 *
 * Types and values are re-exported separately (`export type { }` vs
 * `export { }`): a bundler doing real cross-module analysis (Rollup, for
 * `pnpm build`) errors on re-exporting a name that has no runtime binding,
 * which every `interface`/`type` here is.
 */

export {
  abs,
  acos,
  acosh,
  add,
  all,
  and,
  any,
  asin,
  asinh,
  assertBlockScope,
  atan,
  atanh,
  attribute,
  attributeRaw,
  bitAnd,
  bitNot,
  bitOr,
  bitXor,
  bool,
  Break,
  builtinFragDepth,
  builtinPosition,
  bvec2,
  bvec3,
  bvec4,
  cbrt,
  ceil,
  clamp,
  Continue,
  cos,
  cosh,
  cross,
  degrees,
  determinant,
  dFdx,
  dFdy,
  difference,
  Discard,
  distance,
  div,
  dot,
  element,
  EPSILON,
  equal,
  exp,
  exp2,
  faceForward,
  float,
  floor,
  Fn,
  For,
  fract,
  fragCoord,
  fwidth,
  greaterThan,
  greaterThanEqual,
  HALF_PI,
  If,
  INFINITY,
  int,
  interleavedGradientNoise,
  inverse,
  inverseSqrt,
  inversesqrt,
  isAttributeNode,
  isUniformNode,
  isVaryingNode,
  ivec2,
  ivec3,
  ivec4,
  length,
  lengthSq,
  lessThan,
  lessThanEqual,
  log,
  log2,
  Loop,
  luminance,
  mat2,
  mat2x3,
  mat2x4,
  mat3,
  mat3x2,
  mat3x4,
  mat4,
  mat4x2,
  mat4x3,
  max,
  min,
  mix,
  mod,
  mul,
  negate,
  Node,
  normalize,
  not,
  notEqual,
  oneMinus,
  or,
  output,
  PI,
  PI2,
  pow,
  pow2,
  pow3,
  pow4,
  premultiplyAlpha,
  radians,
  rand,
  reciprocal,
  reflect,
  refract,
  Return,
  round,
  saturate,
  screenCoordinate,
  screenSize,
  screenUV,
  select,
  storage,
  invocationIndex,
  shiftLeft,
  shiftRight,
  sign,
  sin,
  sinh,
  smoothstep,
  sqrt,
  step,
  sub,
  Switch,
  tan,
  tanh,
  textureLoad,
  textureSize,
  time,
  transpose,
  trunc,
  TWO_PI,
  uint,
  uniform,
  uniformArray,
  uniformRaw,
  unpremultiplyAlpha,
  uv,
  uvec2,
  uvec3,
  uvec4,
  var_,
  varying,
  varyingRaw,
  vec2,
  vec3,
  vec4,
  While,
  xor,
} from "./core";
export type {
  AttributeNode,
  BaseNode,
  BooleanLike,
  StorageAccess,
  StorageNode,
  FloatLike,
  IntLike,
  ISampler2DLike,
  IVec2Like,
  IVec3Like,
  IVec4Like,
  Mat3Like,
  Mat4Like,
  Sampler2DLike,
  Sampler3DLike,
  ShaderType,
  UintLike,
  UniformArrayNode,
  UniformNode,
  USampler3DLike,
  UVec2Like,
  UVec3Like,
  UVec4Like,
  VariableNode,
  VaryingNode,
  Vec2Like,
  Vec3Like,
  Vec4Like,
} from "./core";

export type { CompileFnOptions, VertexRoot } from "./backends/shared";

export { compileGLSL } from "./backends/glsl";
export type { CompileGLSLOptions, GLSLPrecision } from "./backends/glsl";

export { compileWGSL, wgslUniformLayout } from "./backends/wgsl";
export type { CompileWGSLOptions, WgslUniformDeclaration, WgslUniformMember } from "./backends/wgsl";

export { compileJS, compileJSFn } from "./backends/js";
export type { CompileJSOptions } from "./backends/js";

export type {
  CpuDrawBuffer,
  CpuRenderer,
  CpuShaderContext,
  CpuShaderResult,
  CpuTextureData,
  CpuTextureWrap,
} from "./backends/cpu";

export { compileGLSLFn, compileWGSLFn } from "./standalone-fn";

export { compileWasm, compileWasmFn, instantiateWasm } from "./backends/wasm";
export type { CompiledWasm, WasmParam } from "./backends/wasm";

export type { Adapter, TypedArray } from "./backends/adapter";
export { createCpu } from "./backends/adapter-cpu";
export { createGlsl } from "./backends/adapter-glsl";
export type { GlslDrawOptions } from "./backends/adapter-glsl";
export type { AdapterResult as CpuAdapterResult } from "./backends/adapter-cpu";

